In [2]:
import torch

In [11]:
model = torch.load("./runs/rock_test1/models/model_0.pt", weights_only=True)
model

{'model_state_dict': OrderedDict([('std', tensor([0.9938], device='cuda:0')),
              ('actor.0.weight',
               tensor([[ 0.1337,  0.1821,  0.1952,  ...,  0.1541, -0.0722, -0.1436],
                       [-0.1416,  0.0724,  0.0369,  ..., -0.0907, -0.1643, -0.1062],
                       [ 0.1828,  0.2082, -0.1983,  ..., -0.1836,  0.1807,  0.0653],
                       ...,
                       [ 0.0940, -0.1093,  0.1185,  ..., -0.1441, -0.1906,  0.2107],
                       [ 0.0026, -0.2314,  0.1631,  ...,  0.0331, -0.2209, -0.0410],
                       [ 0.1552,  0.0148,  0.1094,  ...,  0.0939, -0.0112, -0.0699]],
                      device='cuda:0')),
              ('actor.0.bias',
               tensor([ 0.0671,  0.1042,  0.1805, -0.0413,  0.1577, -0.0867,  0.1756, -0.1713,
                        0.0553, -0.0640,  0.1681,  0.1564,  0.0147,  0.0958, -0.1713,  0.1403,
                        0.0277,  0.0243, -0.0468, -0.0042,  0.1371,  0.0973,  0.0763,  0

In [15]:
model["model_state_dict"]

OrderedDict([('std', tensor([0.9938], device='cuda:0')),
             ('actor.0.weight',
              tensor([[ 0.1337,  0.1821,  0.1952,  ...,  0.1541, -0.0722, -0.1436],
                      [-0.1416,  0.0724,  0.0369,  ..., -0.0907, -0.1643, -0.1062],
                      [ 0.1828,  0.2082, -0.1983,  ..., -0.1836,  0.1807,  0.0653],
                      ...,
                      [ 0.0940, -0.1093,  0.1185,  ..., -0.1441, -0.1906,  0.2107],
                      [ 0.0026, -0.2314,  0.1631,  ...,  0.0331, -0.2209, -0.0410],
                      [ 0.1552,  0.0148,  0.1094,  ...,  0.0939, -0.0112, -0.0699]],
                     device='cuda:0')),
             ('actor.0.bias',
              tensor([ 0.0671,  0.1042,  0.1805, -0.0413,  0.1577, -0.0867,  0.1756, -0.1713,
                       0.0553, -0.0640,  0.1681,  0.1564,  0.0147,  0.0958, -0.1713,  0.1403,
                       0.0277,  0.0243, -0.0468, -0.0042,  0.1371,  0.0973,  0.0763,  0.1860,
                      -0.10

In [17]:
for k, v in model["model_state_dict"].items():
    print(k, v.shape)

# a0w = model["model_state_dict"]["actor.0.weight"]
# # a1w = model["model_state_dict"]["actor.1.weight"]

# len(a0w)

std torch.Size([1])
actor.0.weight torch.Size([512, 18])
actor.0.bias torch.Size([512])
actor.2.weight torch.Size([256, 512])
actor.2.bias torch.Size([256])
actor.4.weight torch.Size([128, 256])
actor.4.bias torch.Size([128])
actor.6.weight torch.Size([1, 128])
actor.6.bias torch.Size([1])
critic.0.weight torch.Size([512, 18])
critic.0.bias torch.Size([512])
critic.2.weight torch.Size([256, 512])
critic.2.bias torch.Size([256])
critic.4.weight torch.Size([128, 256])
critic.4.bias torch.Size([128])
critic.6.weight torch.Size([1, 128])
critic.6.bias torch.Size([1])
